appConfigFile:
  enabled: true
  data:
    - volumeName: service-config
      mountPath: /app/app/internal/config
      fileName: configuration.yml
      fileContent: |
        app:
          name: campaing-consumer-api
        server:
          port: 0.0.0.0:8080
        health:
          port: 0.0.0.0:8081
        timeLocation: America/Sao_Paulo
        database:
          host: pg-campaing-consumer-api.sandbox.com
          port: 5432
          username: ads-campaing-app
          database: ads-campaing-db
          conn:
            min: 1
            max: 1
            lifetime: 120s
            idletime: 120s
        aws:
          region: us-east-1
          sqs:
            queue: https://sqs.us-east-1.amazonaws.com/queue_campaing